services:
  owner-app:
    env_file:
      - .env
    build: .
    container_name: carwash-owner-app
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    networks:
      - carwash-network

  db:
    image: postgres:17
    container_name: carwash-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - carwash-network

volumes:
  postgres-data:

networks:
  carwash-network:
    name: carwash-network
    driver: bridge