spring:
  application:
    name: carava-carwash-owner
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.carava.carwash: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG